import {
  FaBroadcastTower,
  FaRegFilePdf,
  FaRegBuilding,
  FaRegCalendarAlt,
  FaVectorSquare,
  FaTransgenderAlt,
  FaUsers,
} from "react-icons/fa";

import React from "react";
export const feasibilityStudyData = {
  INVEST_SITE_POLYGON: {
    name: "الأراضي الاستثمارية",
    outFields: [
      "SITE_SUBTYPE",
      "SITE_MAIN_ACTIVITY_FORAS",
      "PARCEL_PLAN_NO",
      "SITE_SUB_ACTIVITY",
      "PLAN_NO",
      "SITE_COMMON_USE",
      "DISTRICT_NAME",
      "USING_SYMBOL",
      "MUNICIPALITY_NAME",
      "SITE_LAT_COORD",
      "SITE_LONG_COORD",
      "SITE_AREA",
    ],
    hideFields: [
      "OBJECTID",
      "SITE_GEOSPATIAL_ID",
      "STREET_NAME",
      "SITE_STATUS",
      "CONTRACT_NUMBER",
      "AUCTION_NO",
      "SITE_MAIN_ACTIVITY_FORAS",
      "SITE_ACTIVITY_ISIC",
      "NORTH_BOUNDARY_LENGTH",
      "NORTH_BOUNDARY_DESC",
      "EAST_BOUNDARY_LENGTH",
      "EAST_BOUNDARY_DESC",
      "SOUTH_BOUNDARY_LENGTH",
      "SOUTH_BOUNDARY_DESC",
      "WEST_BOUNDARY_LENGTH",
      "WEST_BOUNDARY_DESC",
      "NORTH_BOUNDARY_DESCRIPTION",
      "EAST_BOUNDARY_DESCRIPTION",
      "SOUTH_BOUNDARY_DESCRIPTION",
      "WEST_BOUNDARY_DESCRIPTION",
    ],
    hideAlaisOutFields: ["المميز المكاني للموقع الاستثمارى"],
    title: ["SITE_ACTIVITY", "CONTRACT_NUMBER", "PROJECT_NO"],
    subTitle: ["MUNICIPALITY_NAME", "DISTRICT_NAME"],
    filter: "SITE_GEOSPATIAL_ID",
    filteralias: "المميز المكاني للموقع الاستثمارى",
    aliasOutFields: [
      'نوع الموقع',
      'الاستخدام الرئيسي',
      'رقم القطعة',
      'الاستخدام الفرعي',
      'رقم المخطط',
      'الاستخدام الشائع',
      'الحي',
      'الاشتراطات',
      'البلدية',
      "احداثى دائرة العرض للمركز الهندسى",
      "احداثى خط الطول للمركز الهندسى",
      'المساحة',
    ],
    shownDataInReport:[
      {
        label1:'نوع الموقع',
        fieldName1:"SITE_SUBTYPE",
      
        label2: 'الاستخدام الرئيسي',
        fieldName2:"SITE_MAIN_ACTIVITY_FORAS"
      },
      {
        label1: 'رقم القطعة',
        fieldName1:"PARCEL_PLAN_NO",
        label2:'الاستخدام الفرعي',
        fieldName2:"SITE_SUB_ACTIVITY",
      },
      {
        label1:'رقم المخطط',
        fieldName1:"PLAN_NO",
      
        label2: 'الاستخدام الشائع',
        fieldName2:"SITE_COMMON_USE"
      },
      {
        label1: 'الحي',
        fieldName1:"DISTRICT_NAME",
        label2:'الاشتراطات',
        fieldName2:"USING_SYMBOL",
      },
      {
        label1: 'البلدية',
        fieldName1:"MUNICIPALITY_NAME",
      
        label2: 'الاحداثيات',
        fieldName2: "Coordinates"
      },
      {
        label1:'المساحة',
        fieldName1:"SITE_AREA",
      
        label2: 'رابط الموقع',
        fieldName2:"googleMapsSite"
      },
    ]
  },
  TBL_BUILD_DETAILS: {
    isHidden: true,
    name: "بيانات المبنى التفصيلية",
    outFields: [
      "BUILD_ACTUAL_USE",
      "BUILD_USE",    //توصيف الموقع
      "LOCATION_STATUS",
      "BUILD_TYPE",
      "BUILDING_STATUS",
      // "BUILD_SURVEY",
      "BUILD_FLOOR_COUNT",
      "BUILD_UNIT_COUNT",
      "FLOOR_STATUS",
      "BUILD_SERVICES",
      "BUILD_REPORT",
      "IMAGE_URL"
    ],
    aliasOutFields: [
      "الاستخدام الحالي",
      "توصيف الموقع ",
      "حالة الموقع",
      " نوعية البناء ",
      "حالة المبني",
      // "ملاحظات المساح" ,
      "عدد الأدوار",
      "عدد الوحدات",
      "حالة العقار",
      "خدمات العقار",
      "ملاحظات التقرير",
      'صورة الموقع'
    ],
    shownDataInReport:[
      {
        label1:"الاستخدام الحالي",
        fieldName1:"BUILD_ACTUAL_USE",
      
        label2: "طبيعة الموقع ",
        fieldName2:"LOCATION_STATUS"
      },
      {
        label1: "وصف الموقع",
        fieldName1:"BUILD_USE",
        label2:" نوع البناء ",
        fieldName2:"BUILD_TYPE",
      },
      {
        label1:"حالة المبني",
        fieldName1:"BUILDING_STATUS",
      
        label2: "حالة العقار",
        fieldName2:"FLOOR_STATUS"
      },
      {
        label1: "عدد الوحدات",
        fieldName1:"BUILD_UNIT_COUNT",
        label2:"عدد الأدوار",
        fieldName2:"BUILD_FLOOR_COUNT",
      },
     
    ]
  },
  TBL_CONTRACTS: {
    shownDataInReport:[
      {
        label1:'رقم الملف',
        fieldName1:"FILE_NUMBER",
      
        label2: 'نهاية العقد',
        fieldName2:"END_DATEG"
      },
      {
        label1: 'حالة العقد',
        fieldName1:"CONTRACT_STATUS",
        label2:'المساحة م2',
        fieldName2:"CONTRACT_AREA",
      },
      {
        label1:'النشاط بالعقد',
        fieldName1:"NAME",
      
        label2: 'القيمة الإيجارية',
        fieldName2:"CONTRACT_VALUE"
      },
      {
        label1: 'مدة العقد',
        fieldName1:"PERIOD",
        label2:'آخر سداد',
        fieldName2:"LAST_INSTL_DATE",
      },
    ]
  },
}
export const layersSetting = {
  INVEST_SITE_POLYGON: {
    showToc: true,
    name: "الأراضي الاستثمارية",
    outFields: [
      "OBJECTID",
      "MUNICIPALITY_NAME",
      "DISTRICT_NAME",
      "PLAN_NO",
      "PARCEL_PLAN_NO",
      "STREET_NAME",
      "SITE_AREA",
      "SITE_STATUS",
      "SITE_SUBTYPE",
      "CONTRACT_NUMBER",
      "AUCTION_NO",
      "SITE_LAT_COORD",
      "SITE_LONG_COORD",
      "SITE_MAIN_ACTIVITY_FORAS",
      "SITE_ACTIVITY_ISIC",
      "SITE_COMMON_USE",
      "SITE_GEOSPATIAL_ID",
      "NORTH_BOUNDARY_LENGTH",
      "NORTH_BOUNDARY_DESC",
      "EAST_BOUNDARY_LENGTH",
      "EAST_BOUNDARY_DESC",
      "SOUTH_BOUNDARY_LENGTH",
      "SOUTH_BOUNDARY_DESC",
      "WEST_BOUNDARY_LENGTH",
      "WEST_BOUNDARY_DESC",
      "NORTH_BOUNDARY_DESCRIPTION",
      "EAST_BOUNDARY_DESCRIPTION",
      "SOUTH_BOUNDARY_DESCRIPTION",
      "WEST_BOUNDARY_DESCRIPTION",
      "FILE_NUMBER"
      //'GROUP_CODE',
    ],
    hideFields: [
      "SITE_GEOSPATIAL_ID",
      "OBJECTID",
      "NORTH_BOUNDARY_LENGTH",
      "NORTH_BOUNDARY_DESC",
      "EAST_BOUNDARY_LENGTH",
      "EAST_BOUNDARY_DESC",
      "WEST_BOUNDARY_LENGTH",
      "WEST_BOUNDARY_DESC",
      "SOUTH_BOUNDARY_LENGTH",
      "SOUTH_BOUNDARY_DESC",
      "NORTH_BOUNDARY_DESCRIPTION",
      "EAST_BOUNDARY_DESCRIPTION",
      "SOUTH_BOUNDARY_DESCRIPTION",
      "WEST_BOUNDARY_DESCRIPTION",
      "FILE_NUMBER"
    ],
    hideAlaisOutFields: ["المميز المكاني للموقع الاستثمارى"],
    title: ["SITE_ACTIVITY", "CONTRACT_NUMBER", "PROJECT_NO"],
    subTitle: ["MUNICIPALITY_NAME", "DISTRICT_NAME"],
    dependecies: [
      {
        name: "SDE.TBL_Contracts",
        Component: <FaRegFilePdf />,
        filter: "SITE_GEOSPATIAL_ID",
        filteralias: "المميز المكاني للموقع الاستثمارى",
        isTable: true,
        tooltip: "",
      },
      {
        name: "INVEST_SITE_BOUNDARY",
        Component: <FaVectorSquare color="#607D8B" />,
        filter: "SITE_GEOSPATIAL_ID",
        filteralias: "المميز المكاني للموقع الاستثمارى",
        tooltip: "Location Limit",
      },
      {
        name: "SDE.TBL_Building_Data",
        Component: <FaRegBuilding color="#795548" />,
        filter: "SITE_GEOSPATIAL_ID",
        isTable: true,
        filteralias: "المميز المكاني للموقع الاستثمارى",
        valueDomain: "المبانى",
        value: "1",
        tooltip: "building details",
      },
      {
        name: "SDE.TBL_Borads",
        Component: <FaRegCalendarAlt color="coral" />,
        filter: "SITE_GEOSPATIAL_ID",
        tooltip: "ad details",
        isTable: true,
        filteralias: "المميز المكاني للموقع الاستثمارى",
        valueDomain: "اللوحات الاعلانية",
        value: "2",
      },
      {
        name: "SDE.TBL_Towers",
        tooltip: "Building Tower",
        filter: "SITE_GEOSPATIAL_ID",
        isTable: true,
        filteralias: "المميز المكاني للموقع الاستثمارى",
        Component: <FaBroadcastTower color="orange" />,
        valueDomain: "ابراج الاتصالات",
        value: "3",
      },
      {
        name: "SDE.TBL_BoardsGroup",
        Component: <FaTransgenderAlt color="green" />,
        tooltip: "group data",
        filter: "GROUP_CODE",
        filteralias: "GROUP_CODE",
        isTable: true,
        isSameParent: true,
      },
    ],
    filter: "SITE_GEOSPATIAL_ID",
    filteralias: "المميز المكاني للموقع الاستثمارى",
    aliasOutFields: [
      "اسم البلدية",
      "اسم الحى",
      "رقم المخطط",
      "رقم قطعة الأرض بالمخطط",
      "اسم الشارع",
      "المساحة م2",
      "حالة الموقع",
      "نوع الموقع الاستثمارى",
      "رقم العقد",
      "رقم المزايدة",
      "احداثى دائرة العرض للمركز الهندسى",
      "احداثى خط الطول للمركز الهندسى",
      "النشاط من فرص",
      "النشاط من ISIC",
      "النشاط الشائع",
      
      //'وصف اشتراط البناء'
    ],
  },
  Advertising_boards: {
    showToc: true,
    name: "اللوحات الاعلانية",
    outFields: [
      "MUNICIPALITY_NAME",
      "DISTRICT_NAME",
      "PLAN_NO",
      "PARCEL_PLAN_NO",
      "STREET_NAME",
      "SITE_ACTIVITY",
      "SITE_STATUS",
      "SITE_SUBTYPE",
      "CONTRACT_NUMBER",
      "PROJECT_NO",
      "SITE_GEOSPATIAL_ID",
      "GROUP_CODE",
      "SITE_LAT_COORD",
      "SITE_LONG_COORD",
    ],
    title: ["SITE_ACTIVITY", "CONTRACT_NUMBER", "PROJECT_NO"],
    subTitle: ["MUNICIPALITY_NAME", "DISTRICT_NAME"],
    dependecies: [
      {
        name: "SDE.TBL_Contracts",
        Component: <FaRegFilePdf />,
        filter: "SITE_GEOSPATIAL_ID",
        filteralias: "المميز المكاني للموقع الاستثمارى",
        isTable: true,
      },
      {
        name: "SDE.TBL_Building_Data",
        Component: <FaRegBuilding />,
        filter: "SITE_GEOSPATIAL_ID",
        isTable: true,
        filteralias: "المميز المكاني للموقع الاستثمارى",
        valueDomain: "المبانى",
        value: "1",
      },
      {
        name: "SDE.TBL_Borads",
        icon: "fa fa-calendar-o",
        Component: <FaRegCalendarAlt />,
        filter: "SITE_GEOSPATIAL_ID",
        tooltip: "ad details",
        isTable: true,
        filteralias: "المميز المكاني للموقع الاستثمارى",
        valueDomain: "اللوحات الاعلانية",
        value: "2",
      },
      {
        name: "SDE.TBL_Towers",
        Component: <FaBroadcastTower />,
        filter: "SITE_GEOSPATIAL_ID",
        isTable: true,
        filteralias: "المميز المكاني للموقع الاستثمارى",
        valueDomain: "ابراج الاتصالات",
        value: "3",
      },
      {
        name: "SDE.TBL_BoardsGroup",
        icon: "fa fa-users",
        filter: "GROUP_CODE",
        filteralias: "GROUP_CODE",
        tooltip: "group data",
        isTable: true,
        isSameParent: true,
      },
    ],
    filter: "SITE_GEOSPATIAL_ID",
    filteralias: "المميز المكاني للموقع الاستثمارى",
    aliasOutFields: [
      "اسم البلدية",
      "اسم الحى",
      "رقم المخطط",
      "رقم قطعة الأرض بالمخطط",
      "اسم الشارع الرئيسى",
      "النشاط الاستثمارى",
      "حالة الموقع",
      "نوع الموقع اللاستثمارى",
      "رقم العقد",
      "رقم المزايدة",
      "احداثى دائرة العرض للمركز الهندسى",
      "احداثى خط الطول للمركز الهندسى",
    ],
  },
  collect_invest: {
    isSearchable: true,
    name: "",
    outFields: [
      "OBJECTID",
      "MUNICIPLAITY_NAME",
      "DISTRICT_NAME",
      "PLAN_NO",
      "STREET_NAME",
      "PARCEL_PLAN_NO",
      "LAT_COORDINATE",
      "LONG_COORDINATE",
      "INVEST_ACTIVITY",
      "SITE_AREA",
      "NORTH_BOUND_DESC",
      "EAST_BOUND_DESC",
      "WEST_BOUND_DESC",
      "SOUTH_BOUND_DESC",
      "PROPERTY_ID",
    ],
    aliasOutFields: [
      "اسم البلدية",
      "اسم الحي",
      "رقم المخطط",
      "الشارع",
      "رقم القطعة",
      "إحداثي خط الطول",
      "إحداثي دائرة العرض",
      "النشاط الأستثماري",
      "مساحة الموقع",
    ],
    hideFields: [
      "OBJECTID",
      "NORTH_BOUND_DESC",
      "EAST_BOUND_DESC",
      "WEST_BOUND_DESC",
      "SOUTH_BOUND_DESC",
      "PROPERTY_ID",
    ],
  },
  Boards: {
    isSearchable: true,
    name: "",
    outFields: [
      "OBJECTID",
      "MUNICIPLAITY_NAME",
      "DISTRICT_NAME",
      "PLAN_NO",
      "STREET_NAME",
      "SITE_LAT_COORDINATE",
      "SITE_LONG_COORDINATE",
      "INVEST_ACTIVITY",
      "SITE_AREA",
      "INVEST_STATUS",
      "PROPERTY_ID",
    ],
    aliasOutFields: [
      "اسم البلدية",
      "اسم الحي",
      "رقم المخطط",
      "الشارع",
      "إحداثي خط الطول",
      "إحداثي دائرة العرض",
      "النشاط الاستثماري",
      "مساحة الموقع",
    ],
    hideFields: ["OBJECTID", "PROPERTY_ID", "INVEST_STATUS"],
  },

  INVEST_SITE_BOUNDARY: {
    isHidden: true,
    name: "حدود الارض",
    outFields: [
      "BOUNDARY_DIRECTION",
      "BOUNDARY_LENGTH",
      "BOUNDARY_DESCRIPTION",
    ],
    aliasOutFields: ["اتجاه الحد", "طول الحد - م ", "وصف الحد"],
  },
  collect_INVEST_SITE_BOUNDARY: {
    isHidden: true,
    name: "حدود الارض",
    outFields: ["BOUNDARY_DIRECTION", "BOUNDARY_DESCRIPTION"],
    aliasOutFields: ["اتجاه الحد", "وصف الحد"],
  },
  INVEST_SITE_CORNER: {
    isHidden: true,
    name: "حدود الارض",
    outFields: ["CORNER_NO", "XUTM_COORD", "YUTM_COORD"],
    aliasOutFields: [" رقم النقطة", "الإحداثي السينى", "الإحداثي الصادي"],
  },
  TBL_BUILD_DETAILS: {
    isHidden: true,
    name: "بيانات المبنى التفصيلية",
    outFields: [
      "BUILD_ACTUAL_USE",
      "BUILD_USE",    //توصيف الموقع
      "LOCATION_STATUS",
      "BUILD_TYPE",
      "BUILDING_STATUS",
      // "BUILD_SURVEY",
      "BUILD_FLOOR_COUNT",
      "BUILD_UNIT_COUNT",
      "FLOOR_STATUS",
      "BUILD_SERVICES",
      "BUILD_REPORT",
      "IMAGE_URL"
    ],
    aliasOutFields: [
      "الاستخدام الحالي",
      "توصيف الموقع ",
      "حالة الموقع",
      " نوعية البناء ",
      "حالة المبني",
      // "ملاحظات المساح" ,
      "عدد الأدوار",
      "عدد الوحدات",
      "حالة العقار",
      "خدمات العقار",
      "ملاحظات التقرير",
      'صورة الموقع'
    ],
  },
  TBL_CONTRACTS: {
    isHidden: true,
    name: "بيانات العقد",
    outFields: [
    
    ],
    aliasOutFields: [
    ],
  },
};
